#pragma once
#define FMT_CLEAR "\e[0m"
#define BOLD "\e[1m"
#define ITALIC "\e[4m"
#define REV "\e[7m"
#define BOLD_RED "\e[1;31m"
#define BOLD_GREEN "\e[1;32m"
#define BOLD_BLUE "\e[1;33m"
#define BOLD_YELLOW "\e[1;34m"
#define BG_WHITE_FG_BLACK "\e[47;30m"

#define LIGREY "\e[90m"
#define PURPLE "\e[36m"
#define CYAN "\e[34m"
#define GREEN "\e[32m"
#define YELLOW "\e[33m"
#define PUPLE2 "\e[35m"
#define IYELLOW "\e[7;33m"
#define PINK "\e[35m"
#define LIRED "\e[91m"
#define RED "\e[31m"
#define DWHITE "\e[96m"
#define BOLD_DWHITE "\e[1;96m"
#define UNDERLINE "\e[4m"
