#pragma once
// clang-format off
    #define SET_ERROR(res, err_status)\
    LOG_ERROR("%d %s",HttpStatus_##err_status,#err_status);\
    res.hasError=true;\
    res.err = (HttpError){\
        .code = HttpStatus_##err_status,\
        .src = (ErrorSource){\
            .line= __LINE__,\
            .name= __FILE_NAME__,\
        },\
    };
    #define SET_RESP_ERROR(res, err_status)\
    LOG_ERROR("%d %s",HttpStatus_##err_status,#err_status);\
    res.status = HttpStatus_##err_status;\
    res.headers = nullptr;  /* not sure about this */\
    res.header_count = 0;   /* not sure about this */\
    res.resource_fptr = nullptr;\
    return res;

typedef enum {
    HttpStatus_CONTINUE                           ,
    HttpStatus_SWITCHING_PROTOCOLS                ,
    HttpStatus_PROCESSING                         ,
    HttpStatus_EARLY_HINTS                        ,
    HttpStatus_UPLOAD_RESUMPTION_SUPPORTED        ,
    HttpStatus_OK                                 ,
    HttpStatus_CREATED                            ,
    HttpStatus_ACCEPTED                           ,
    HttpStatus_NON_AUTHORITATIVE_INFORMATION      ,
    HttpStatus_NO_CONTENT                         ,
    HttpStatus_RESET_CONTENT                      ,
    HttpStatus_PARTIAL_CONTENT                    ,
    HttpStatus_MULTI_STATUS                       ,
    HttpStatus_ALREADY_REPORTED                   ,
    HttpStatus_IM_USED                            ,
    HttpStatus_MULTIPLE_CHOICES                   ,
    HttpStatus_MOVED_PERMANENTLY                  ,
    HttpStatus_FOUND                              ,
    HttpStatus_SEE_OTHER                          ,
    HttpStatus_NOT_MODIFIED                       ,
    HttpStatus_USE_PROXY                          ,
    HttpStatus_UNUSED                             ,
    HttpStatus_TEMPORARY_REDIRECT                 ,
    HttpStatus_PERMANENT_REDIRECT                 ,
    HttpStatus_BAD_REQUEST                        ,
    HttpStatus_UNAUTHORIZED                       ,
    HttpStatus_PAYMENT_REQUIRED                   ,
    HttpStatus_FORBIDDEN                          ,
    HttpStatus_NOT_FOUND                          ,
    HttpStatus_METHOD_NOT_ALLOWED                 ,
    HttpStatus_NOT_ACCEPTABLE                     ,
    HttpStatus_PROXY_AUTHENTICATION_REQUIRED      ,
    HttpStatus_REQUEST_TIMEOUT                    ,
    HttpStatus_CONFLICT                           ,
    HttpStatus_GONE                               ,
    HttpStatus_LENGTH_REQUIRED                    ,
    HttpStatus_PRECONDITION_FAILED                ,
    HttpStatus_CONTENT_TOO_LARGE                  ,
    HttpStatus_URI_TOO_LONG                       ,
    HttpStatus_UNSUPPORTED_MEDIA_TYPE             ,
    HttpStatus_RANGE_NOT_SATISFIABLE              ,
    HttpStatus_EXPECTATION_FAILED                 ,
    HttpStatus_IM_A_TEAPOT                        ,
    HttpStatus_MISDIRECTED_REQUEST                ,
    HttpStatus_UNPROCESSABLE_CONTENT              ,
    HttpStatus_LOCKED                             ,
    HttpStatus_FAILED_DEPENDENCY                  ,
    HttpStatus_TOO_EARLY                          ,
    HttpStatus_UPGRADE_REQUIRED                   ,
    HttpStatus_UNASSIGNED_1                       ,
    HttpStatus_PRECONDITION_REQUIRED              ,
    HttpStatus_TOO_MANY_REQUESTS                  ,
    HttpStatus_UNASSIGNED_2                       ,
    HttpStatus_REQUEST_HEADER_FIELDS_TOO_LARGE    ,
    HttpStatus_UNAVAILABLE_FOR_LEGAL_REASONS      ,
    HttpStatus_INTERNAL_SERVER_ERROR              ,
    HttpStatus_NOT_IMPLEMENTED                    ,
    HttpStatus_BAD_GATEWAY                        ,
    HttpStatus_SERVICE_UNAVAILABLE                ,
    HttpStatus_GATEWAY_TIMEOUT                    ,
    HttpStatus_HTTP_VERSION_NOT_SUPPORTED         ,
    HttpStatus_VARIANT_ALSO_NEGOTIATES            ,
    HttpStatus_INSUFFICIENT_STORAGE               ,
    HttpStatus_LOOP_DETECTED                      ,
    HttpStatus_UNASSIGNED_3                       ,
    HttpStatus_NOT_EXTENDED                       ,
    HttpStatus_NETWORK_AUTHENTICATION_REQUIRED    ,
}HttpStatus;


static const char* HttpStatus_toStr[] = {
"100",
"101",
"102",
"103",
"104",
"200",
"201",
"202",
"203",
"204",
"205",
"206",
"207",
"208",
"226",
"300",
"301",
"302",
"303",
"304",
"305",
"306",
"307",
"308",
"400",
"401",
"402",
"403",
"404",
"405",
"406",
"407",
"408",
"409",
"410",
"411",
"412",
"413",
"414",
"415",
"416",
"417",
"418",
"421",
"422",
"423",
"424",
"425",
"426",
"427",
"428",
"429",
"430",
"431",
"451",
"500",
"501",
"502",
"503",
"504",
"505",
"506",
"507",
"508",
"509",
"510",
"511",
};
