#pragma once
// clang-format off
typedef enum {
    CONTINUE                           = 100,
    SWITCHING_PROTOCOLS                = 101,
    PROCESSING                         = 102,
    EARLY_HINTS                        = 103,
    UPLOAD_RESUMPTION_SUPPORTED        = 104,
    OK                                 = 200,
    CREATED                            = 201,
    ACCEPTED                           = 202,
    NON_AUTHORITATIVE_INFORMATION      = 203,
    NO_CONTENT                         = 204,
    RESET_CONTENT                      = 205,
    PARTIAL_CONTENT                    = 206,
    MULTI_STATUS                       = 207,
    ALREADY_REPORTED                   = 208,
    IM_USED                            = 226,
    MULTIPLE_CHOICES                   = 300,
    MOVED_PERMANENTLY                  = 301,
    FOUND                              = 302,
    SEE_OTHER                          = 303,
    NOT_MODIFIED                       = 304,
    USE_PROXY                          = 305,
    UNUSED                             = 306,
    TEMPORARY_REDIRECT                 = 307,
    PERMANENT_REDIRECT                 = 308,
    BAD_REQUEST                        = 400,
    UNAUTHORIZED                       = 401,
    PAYMENT_REQUIRED                   = 402,
    FORBIDDEN                          = 403,
    NOT_FOUND                          = 404,
    METHOD_NOT_ALLOWED                 = 405,
    NOT_ACCEPTABLE                     = 406,
    PROXY_AUTHENTICATION_REQUIRED      = 407,
    REQUEST_TIMEOUT                    = 408,
    CONFLICT                           = 409,
    GONE                               = 410,
    LENGTH_REQUIRED                    = 411,
    PRECONDITION_FAILED                = 412,
    CONTENT_TOO_LARGE                  = 413,
    URI_TOO_LONG                       = 414,
    UNSUPPORTED_MEDIA_TYPE             = 415,
    RANGE_NOT_SATISFIABLE              = 416,
    EXPECTATION_FAILED                 = 417,
    IM_A_TEAPOT                        = 418,
    MISDIRECTED_REQUEST                = 421,
    UNPROCESSABLE_CONTENT              = 422,
    LOCKED                             = 423,
    FAILED_DEPENDENCY                  = 424,
    TOO_EARLY                          = 425,
    UPGRADE_REQUIRED                   = 426,
    UNASSIGNED_1                       = 427,
    PRECONDITION_REQUIRED              = 428,
    TOO_MANY_REQUESTS                  = 429,
    UNASSIGNED_2                       = 430,
    REQUEST_HEADER_FIELDS_TOO_LARGE    = 431,
    UNAVAILABLE_FOR_LEGAL_REASONS      = 451,
    INTERNAL_SERVER_ERROR              = 500,
    NOT_IMPLEMENTED                    = 501,
    BAD_GATEWAY                        = 502,
    SERVICE_UNAVAILABLE                = 503,
    GATEWAY_TIMEOUT                    = 504,
    HTTP_VERSION_NOT_SUPPORTED         = 505,
    VARIANT_ALSO_NEGOTIATES            = 506,
    INSUFFICIENT_STORAGE               = 507,
    LOOP_DETECTED                      = 508,
    UNASSIGNED_3                       = 509,
    NOT_EXTENDED                       = 510,
    NETWORK_AUTHENTICATION_REQUIRED    = 511,
}HttpStatus;


typedef enum {
    HttpRequestMethod_GET,
    HttpRequestMethod_HEAD,
    HttpRequestMethod_OPTIONS,
    HttpRequestMethod_TRACE,
    HttpRequestMethod_PUT,      // UNSAFE!!
    HttpRequestMethod_DELETE,   // UNSAFE!!
    HttpRequestMethod_POST,     // UNSAFE!!
    HttpRequestMethod_PATCH,    // UNSAFE!!
    HttpRequestMethod_CONNECT,  // UNSAFE!!
    HttpRequestMethod__COUNT,  
    HttpRequestMethod_PARSE_ERROR,  
} HttpRequestMethod;

static const char* HttpRequestMethod_toStr[] = {
	"GET",
	"HEAD",
	"OPTIONS",
	"TRACE",
	"PUT",      
	"DELETE",   
	"POST",     
	"PATCH",    
	"CONNECT",  
};

typedef enum {
    HttpVersion_1_1,
    HttpVersion_0_9,
    HttpVersion_1_0,
    HttpVersion_2,
    HttpVersion_3,
    HttpVersion__COUNT,
    HttpVersion__PARSE_ERROR,
} HttpVersion;

static const char* HttpVersion_strs[] = {
	"HttpVersion_1_1",
	"HttpVersion_0_9",
	"HttpVersion_1_0",
	"HttpVersion_2",
	"HttpVersion_3",
};
